#Makefile

#Compiler
CXX = g++

#Flags
COMPILE_FLAG = -std=c++11

#Path
SRC_PATH = ./src/vector.cpp
INCLUDE_PATH = ./include/vector.h

#Executable
BIN_NAME = ./bin/vector

vector: $(SRC_PATH) $(INCLUDE_PATH)
	$(CXX) $(COMPILE_FLAG) $(SRC_PATH) $(INCLUDE_PATH) -o $(BIN_NAME)